#index:
#    path: /
#    controller: App\Controller\DefaultController::index

test_api:
  path: /test/api
  controller: App\Controller\TestController::api

test_jobs:
  path: /test/jobs
  controller: App\Controller\TestController::jobs

script_jobs:
  path: /script/jobs
  controller: App\Controller\ScriptController::addJobs